FROM node:lts-alpine@sha256:2c405ed42fc0fd6aacbe5730042640450e5ec030bada7617beac88f742b6997b

RUN mkdir -p /usr/src/app/node_modules && chown -R node:node /usr/src/app

RUN apk update

RUN npm install --global nodemon

ENV NODE_ENV development

WORKDIR /usr/src/app

COPY package*.json ./

USER node

RUN npm ci --only=production

COPY --chown=node:node ./ /usr/src/app/

CMD ["nodemon", "./src/index.js"]