version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "80:$PORT"
    volumes:
      - node_modules:/home/node/app/node_modules
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - "$PORT:$PORT"
    volumes:
      - node_modules:/home/node/app/node_modules
    command: ["npm", "run", "start.dev"]

volumes:
  node_modules: